version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/var/www
    depends_on:
      - db


  db:
    image: mysql:latest
    container_name: db
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: shukatsu
      MYSQL_USER: shukatsu
      MYSQL_PASSWORD: shukatsu
      MYSQL_ROOT_PASSWORD: local

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports: 
      - 8888:80
    depends_on: 
      - db

volumes:
  mysql-volume:
